### PR TITLE
implemented Linux support via libusb 1.0

### PR DESCRIPTION
**Pull request by nitram509**
Hi,

as discussed in #1 , I've added Linux support.
Sorry for the handful commits, but I prefer to use small steps in development.
The intermediate commits can safely be ignored ;-)

Any feedback is welcome.

Regards
Martin

### CODE REVIEW

**Comment by boombuler** [comment]
Hi,

first of all thanks for the work. But I have a few things to note:
- asArray should be called asSlice (since it returns a slice and not an array)
- the report index is stored in the first byte of of the data if I remember correct. As I started with windows thats how the data is passed. And I implemented it on OSX the same way. So you may need to take the first byte of data as index and pass only data[1:] as report data. (I could be wrong on it but would be great if you could test it...)
- On some lines you just drop the errors from the lib. I would prefer to forward them to the user / programmer who is using the library.

Regards
Florian

**Comment by nitram509** [comment]
Florian, 
thanks for your helpful comments.
I will improve my code according your points.
I prefer to let this PR open, until this is fixed.

Regards
Martin

**Comment by nitram509** [comment]
Florian,

I've improved error handling and method names.

But I struggle with the report index.
Currently, I only have 3 Blinkstick devices available.
They work as expected with the current implementation.

What do you suggest to test report index and data[0] vs. data[1] ?

Martin

**Comment by boombuler** [comment]
Hi,

I don't have any device that requires a different report index then zero.
Could you test if your blinkstick devices work with passing data[1] on index data[0]... 
Though it would be weird if it works :)

**Comment by nitram509** [comment]
Its weird, cause changing hid_linux.go:110 'index=1' doesn't have any influence.
I'm still able to change the color, no matter what index is set.

Passing data[1](line 118) results into wrong colors. e.g. 0x0000ff let the Blinkstick shine green.

Do you think it's safe to merge and mention it as "experimental" in the README?
Maybe someone of the community is able to verify...

What do you think?

**Pull request merged**
